name: Running code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-reproducibility:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run main.py
        run: |
          python3 autoop/tests/main.py

      - name: Run tests
        run: |
          pytest autoop/tests -v
